"""tag_cache_table for delayed_clean

Revision ID: 567dbb21ecbe
Revises: c29749bc62a2
Create Date: 2024-11-05 02:31:28.809942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '567dbb21ecbe'
down_revision: Union[str, None] = 'c29749bc62a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(), nullable=False),
    sa.Column('added_timestamp', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tag_cache_pkey')),
    sa.UniqueConstraint('tag_name', name=op.f('tag_cache_tag_name_key'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_cache')
    # ### end Alembic commands ###
