"""initial migration

Revision ID: c29749bc62a2
Revises: 
Create Date: 2024-11-04 01:18:33.656924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c29749bc62a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('immutable', sa.Boolean(), nullable=True),
    sa.Column('separated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tag_pkey')),
    sa.UniqueConstraint('name', name=op.f('tag_name_key'))
    )
    op.create_table('synonym',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('synonym_tag_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('synonym_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('synonym')
    op.drop_table('tag')
    # ### end Alembic commands ###
